server:
  port: ${server_port:5806}

spring:
  application:
    name: image-service
  profiles:
    include: mongodb

fdfs:
  so-timeout: 1501
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - '${tracker:192.168.1.100:22122}'
  #    - localhost:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153

    #获取连接时的最大等待毫秒数100
    max-wait-millis: 102

image:
  download:
    request-headers:
      Content-Type: image/jpeg
      Upgrade-Insecure-Requests: 1
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
#      Referer: http://www.177piczz.info/html/2018/07/2168507.html
    request-method: GET
    buffer-size: 2048
    retries: 3
    timeout: 30000

# Set log level
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: WARN